---
- name: Deploy app using Docker
  hosts: app
  become: yes
  roles:
    - docker
  tasks:
    - name: Run app
      docker_container:
        name: django_app
        image: timurbabs/django
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
